version: "3"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: default
      PGDATA: /data/postgres
    ports:
      - "5432:5432"